DISABLED_USER_MODULES := \
  libtestplugin \
  temp_layoutlib \
  libmock_ril \
  libI420colorconvert \
  apkcheck \
  elftree \
  jdwpspy \
  a3dconvert \
  libsampleplugin \
  libstagefright_chromium_http \
  libjavacore \
  app_process__asan \
  app_process \
  xaplay \
  backtrace_test \
  interrupter \
  binderAddInts \
  libandroidfw \
  InputDispatcher_test \
  libinputservice \
  InputReader_test \
  bootanimation \
  idmap \
  libc_malloc_debug_leak \
  libandroid_runtime \
  libandroid \
  libandroid_servers \
  libmediandk \
  libsoundpool \
  libfilterfw \
  libfilterpack_imageproc \
  libstagefright_http_support \
  libwilhelm \
  libOpenSLES \
  libOpenMAXAL \
  libopenslestests \
  BufferQueue_test \
  slesTest_% \
  libnative-media-jni \
  xaVideoDecoderCapabilities \
  xaplay \
  libdrmclearkeyplugin \
  ClearKeyDrmUnitTest \
  zipalign \
  qcrilmsgtunnel
